[package]
name = "astras"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
rand = "0.8.5"
phf = { version = "0.11", features = ["macros"] }

[features]
dev = ["bevy/dynamic_linking", "bevy/file_watcher"]
