[package]
name = "astras"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
rand = "0.8.5"
phf = { version = "0.11", features = ["macros"] }
bevy-inspector-egui = "0.23.4"
bevy_mod_picking = "0.18.2"

[features]
dev = ["bevy/dynamic_linking", "bevy/file_watcher"]
